---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - !{ageKey}
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - !{ageKey}
