---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: networking
stringData:
  TUNNEL_ID: "!{cloudflare.tunnel.id}"
  credentials.json: |
    {
      "AccountTag": "!{cloudflare.tunnel.accountTag}",
      "TunnelSecret": "!{cloudflare.tunnel.secret}",
      "TunnelID": "!{cloudflare.tunnel.id}"
    }
