---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: "!{cloudflare.domain}"
  SECRET_ACME_EMAIL: "!{email}"
  SECRET_CLOUDFLARE_TUNNEL_ID: "!{cloudflare.tunnel.id}"
